# Generated by Django 4.0.5 on 2022-07-29 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('writer', models.CharField(blank=True, max_length=22, null=True)),
                ('description', models.TextField(max_length=2222)),
                ('price', models.FloatField(null=True)),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=8888)),
                ('student', models.CharField(blank=True, max_length=299, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'product_programming_book',
            },
        ),
        migrations.CreateModel(
            name='Text_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('writer', models.CharField(max_length=22, null=True)),
                ('description', models.TextField(max_length=2222)),
                ('price', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=8888)),
                ('book_pic', models.ImageField(blank=True, null=True, upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('faculty', models.CharField(max_length=222)),
                ('grade', models.IntegerField()),
                ('section', models.CharField(max_length=222)),
                ('first_ordered_book', models.CharField(blank=True, max_length=20, null=True)),
                ('second_ordered_book', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(blank=True, max_length=111, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('name_of_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
