# Generated by Django 4.0.5 on 2022-07-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history',
        ),
    ]
