# Generated by Django 4.0.5 on 2022-07-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='code_of_book',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
