# Generated by Django 4.0.5 on 2022-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='faculty',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
