# Generated by Django 4.0.5 on 2022-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_personal_info_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming_book',
            name='code_no',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='text_book',
            name='code_no',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='programming_book',
            name='description',
            field=models.TextField(blank=True, max_length=2222, null=True),
        ),
        migrations.AlterField(
            model_name='programming_book',
            name='image_url',
            field=models.CharField(blank=True, max_length=8888, null=True),
        ),
        migrations.AlterField(
            model_name='programming_book',
            name='name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='programming_book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programming_book',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text_book',
            name='description',
            field=models.TextField(blank=True, max_length=2222, null=True),
        ),
        migrations.AlterField(
            model_name='text_book',
            name='image_url',
            field=models.CharField(blank=True, max_length=8888, null=True),
        ),
        migrations.AlterField(
            model_name='text_book',
            name='name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='text_book',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
