# Generated by Django 4.0.5 on 2022-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History_of_book', '0002_history_delete_novels'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='code_no',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
